--- Makefile	2004-04-08 03:42:59.000000000 +0200
+++ Makefile	2009-05-01 23:31:00.106571852 +0200
@@ -1,7 +1,7 @@
 TUNCTL = $(shell [ -e /usr/include/linux/if_tun.h ] && echo tunctl)
 
 SUBDIRS = jail jailtest humfsify mconsole moo port-helper $(TUNCTL) uml_net \
-	uml_router watchdog
+	uml_router watchdog uml_dump
 UMLVER = $(shell date +%Y%m%d)
 TARBALL = uml_utilities_$(UMLVER).tar
 BIN_DIR = /usr/bin
