# Target architecture of the UML tools. Valid values include:
# 32 or 64
# However, note that it may not be possible to compile some tools from the
# source code if no suitable cross-architecture compiler is installed
ARCH?=32
